spring: 
  jpa: 
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect 
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
       
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect 
        temp: 
          use_jdbc_metadata_defaults: false   
        
        
  datasource: 
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URI:jdbc:postgresql://192.168.99.100:5432/postgres}
    username: postgres
    password: 
  
  jackson:
    mapper.infer-property-mutators: false
    serialization: 
      INDENT_OUTPUT: true
      fail-on-empty-beans: false
      
h2:
  console:
    enabled: false           