server: 
  port: ${SERVER_PORT:0}
  use-forward-headers: true
  
eureka: 
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    nonSecurePort: ${server.port}
    preferIpAddress: true
    ip-address: ${SERVER_URI:localhost}
    instanceId: ${spring.application.name}:${random.int}
    metadataMap:
      instanceId: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      
spring: 
  application: 
    name: pixeon-exam-api
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create
        
  datasource: 
    url: jdbc:h2:mem:pixeon;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    initialize: true
  
  jackson:
    mapper.infer-property-mutators: false
    serialization: 
      INDENT_OUTPUT: true
      fail-on-empty-beans: false

h2:
  console:
    enabled: true

logging: 
  pattern: 
    dateformat: yy-MM-dd HH:mm:ss