
INSERT INTO HEALTHCARE_INSTITUTION (ID, NAME, CNPJ, ENABLED, CREATED_DATE, MODIFIED_DATE) VALUES 
(1, 'SOS Cardio',  '70.756.493/0001-70', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

ALTER SEQUENCE INSTITUTION_ID_SEQ RESTART WITH 2;
