version: '3'

services:
  pixeon-discovery:
    image: pixeon-discovery:latest
    build:
      context: ./
      dockerfile: Dockerfile.discovery
    volumes:
      - /data/pixeon-discovery
    ports:
      - "8761:8761"
      
  pixeon-gateway:
    image: pixeon-gateway:latest
    build:
      context: ./
      dockerfile: Dockerfile.gateway
    volumes:
      - /data/pixeon-gateway
    ports:
      - "8080:8080"
  
  pixeon-exam-api:
    image: pixeon-exam-api:latest
    build:
      context: ./
      dockerfile: Dockerfile.exam-api
    volumes:
      - /data/pixeon-exam-api
    environment:
      - API_SERVER_PORT=8081
    ports:
      - "8081:8081"
      